[package]
name = "dbuf-core"
edition.workspace = true
version.workspace = true

[dependencies]
chumsky.workspace = true
logos.workspace = true
unescape.workspace = true

thiserror.workspace = true
strum.workspace = true
strum_macros.workspace = true
regex.workspace = true

[lints]
workspace = true
