[package]
name = "dbuf-gen"
edition.workspace = true
version.workspace = true

[dependencies]
dbuf-core.workspace = true
pretty.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
dbuf-rust-runtime.workspace = true

[lints]
workspace = true
